version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step - removing private files"
     - rm buildspec.yml
     - rm README
     - rm -f .DS_Store
 build:
   commands:
     - aws s3 sync . s3://longevityframework.com --delete
 post_build:
   commands:
     - echo "post_build step"
