version: 0.2
phases:
 build:
   commands:
     - mkdir -p dist
     - rsync -av --exclude='.git' --exclude='buildspec.yml' --exclude='README.md' --exclude='.DS_Store' --exclude='.gitignore' ./ dist/
     - rm -f dist/diet/.diet_template.html
     - rm -f dist/lifestyle/.lifestyle_template.html
     - rm -f dist/supplementation/.supplementation_template.html
     - aws s3 sync dist/ s3://longevityframework.com --delete
 post_build:
   commands:
     - echo "post_build steps"
     - echo "invalidating cloudfront cache"
     - aws cloudfront create-invalidation --distribution-id E3B99XVC6AJLUQ --paths "/*"
